# Generated by Django 2.2 on 2019-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='game',
            name='total_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
