# Generated by Django 2.2 on 2019-05-27 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_page', '0006_delete_usergames'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.FloatField()),
                ('gameid', models.ManyToManyField(to='user_page.Game')),
                ('userid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
