# Generated by Django 2.2 on 2019-05-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='gameid',
        ),
        migrations.AddField(
            model_name='game',
            name='ratingid',
            field=models.ManyToManyField(to='user_page.rating'),
        ),
    ]
