# Generated by Django 2.2 on 2019-05-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0010_auto_20190529_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergames',
            name='name',
            field=models.CharField(default='bob', max_length=5),
        ),
    ]
