# Generated by Django 2.2 on 2019-06-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0011_usergames_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergames',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='usergames',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='UserGames',
        ),
    ]
